interfaces:
  - gi1:
      name: 1,
      description: GigabitEthernet,
      ip: 10.3.255.107,
      mask: 255.255.255.0,
      is_loopback: false

  - lo1:
       name: 1
       description: SoftwareLoopback
       ip: 192.168.7.1
       mask: 255.255.255.0
       is_loopback: true

  - lo0:
      name: 0
      description: SoftwareLoopback
      ip: 7.7.7.7
      mask: 255.255.255.255
      is_loopback: true



ospf:
  process: 1,
  router-id: 7.7.7.7,
  networks:
    - lo0:
      id: 10.3.255.0,
      mask: 0.0.0.255,
      area: 0,

    - lo1:
      id:  7.7.7.7,
      mask: 0.0.0.0,
      area: 0,

    - gi1:
      id: 10.3.255.0,
      mask: 0.0.0.255,
      area: 0

bgp:
  as_number: 7
  network_ip: 192.168.7.0
  neighbors:
    - id: 20.20.20.20
      remote_asn: 20
      max_hops: 2
    - id: 7.7.7.7
      remote_asn: 7
      max_hops: 2
      update_source: 1


